version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: marcosht
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    ports:
      - "27017:27017"
    volumes:
      -/devEnvironment/testes/NestApi/apitest/Docker/Volumes/MongoDB
      
networks: 
    mongo-compose-network:
      driver: bridge